<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

    <parent>
        <artifactId>lutece-global-pom</artifactId>
        <groupId>fr.paris.lutece.tools</groupId>
        <version>7.0.2</version>
    </parent>

    <modelVersion>4.0.0</modelVersion>
    <groupId>fr.paris.lutece.plugins</groupId>
    <artifactId>library-mdph</artifactId>
	<packaging>jar</packaging>
    <version>1.0.1-SNAPSHOT</version>
    <name>Lutece library mdph </name>

    <repositories>
        <repository>
            <id>lutece</id>
            <name>luteceRepository</name>
            <url>https://dev.lutece.paris.fr/maven_repository</url>
            <layout>default</layout>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>fr.paris.lutece</groupId>
            <artifactId>lutece-core</artifactId>
            <version>[5.0.0,7.9.9)</version>
            <type>lutece-core</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>library-httpaccess</artifactId>
            <version>[2.5.2-SNAPSHOT,3.9.9)</version>
            <type>lutece-plugin</type>
        </dependency>
    </dependencies>

    <properties>
        <componentName>GRU Library MDPH</componentName>
        <jiraProjectName>GRUMDPH</jiraProjectName>
        <jiraComponentId>15556</jiraComponentId>
	<sonar.sources>pom.xml,src/java</sonar.sources>
   </properties>
	
    <scm>
        <connection>scm:git:https://github.com/lutece-secteur-public/mdph-library-mdph.git</connection>
        <developerConnection>scm:git:https://github.com/lutece-secteur-public/mdph-library-mdph.git</developerConnection>
        <url>https://github.com/lutece-secteur-public/mdph-library-mdph.git</url>
      <tag>HEAD</tag>
  </scm>
</project>